server:
  port: 8081
  servlet:
    context-path: /jackeroo/api

application:
  version: 1.0.0

# actuator监控配置
management:
  endpoint:
    health:
      # 显示监控指标详情
      show-details: always
  endpoints:
    web:
      exposure:
        # 监控jvm信息、健康状况信息、http请求信息、prometheus监控工具
        include: metrics,health,httptrace,prometheus
  health:
    db:
      enabled: true
    redis:
      enabled: true

spring:
  boot:
    admin:
      client:
        url: http:localhost:8081
  redis-template:
    # 配置RedisService中的RedisTemplate的默认过期时间，单位：s
    timeout: 3600
  session:
    # session有效时间，单位s
    timeout: 3600
    # 相同用户同时在线数量限制，-1表示不限制
    same-user-count: -1
  cache:
    redis:
      # 缓存时间，单位s
      time-to-live: 3600
  devtools:
    restart:
      enabled: false  #关闭热部署
  thymeleaf:
    #默认开启Thymeleaf 的缓存，开发环境需要关闭，不然在开发过程中修改页面不会立刻生效需要重启
    cache: false
  datasource:
    # druid监控页面
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
    # 动态数据源配置
    dynamic:
      # 指定使用druid连接池
      druid:
        #初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat, wall, slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 数据库配置
      datasource:
        # 默认数据源
        master:
          url: jdbc:mysql://127.0.0.1:3306/jackeroo-boot?allowMultiQueries=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password : 123456
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000

mybatis-plus:
  configuration:
    #数据库字段映射java属性名是否开启自动驼峰命名，默认值为true
    map-underscore-to-camel-case: true
    #当有多个参数时，如果没有@Param注解，默认使用参数名作为别名，否则默认使用索引作为别名
    use-actual-param-name: true
  global-config:
    banner: false
    db-config:
      #全局默认的主键类型，分配ID (主键类型为number或string），默认实现为雪花算法
      id-type: assign_id
      #全局逻辑删除的实体字段名，如果entity使用@TableLogic注解可覆盖默认设置字段
      logic-delete-field: delFlag
      #逻辑删除已删除的值（默认值为1）
      logic-delete-value: 1
      #逻辑删除未删除的值（默认值为0）
      logic-not-delete-value: 0
      #表名是否使用驼峰转下划线命名,只对表名生效（默认值为true）
      table-underline: true
  type-aliases-package: cn.hub.jackeroo.**.entity
  mapper-locations:
    - classpath*:cn/hub/jackeroo/**/*Mapper.xml

# 日志等级
logging:
  level:
    cn.hub.jackeroo: debug

jackeroo:
  path:
    #上传文件、图片本地根路径
    upload: /data

