server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: false  #关闭热部署
  thymeleaf:
    #默认开启Thymeleaf 的缓存，开发环境需要关闭，不然在开发过程中修改页面不会立刻生效需要重启
    cache: false
  datasource:
      name: test
      url: jdbc:mysql://rm-bp1984n5236i6zb50wo.mysql.rds.aliyuncs.com:3306/zhidao_test?allowMultiQueries=true&characterEncoding=utf-8&autoReconnect=true
      username: zhidao
      password: Zhidao123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize : 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat, wall, logback
      connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 47.98.215.246
    port: 6379
    password : 123456
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  activemq:
    in-memory: true #基于内存的 ActiveMQ
    pool:
      enabled: false # 不适应连接池
  application:
    name: Spring-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: alex
    password: 123456
    virtual-host: /

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.hub.jackeroo  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true  #自动驼峰命名

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

adminPath : /admin




